
spring.application.name=sa
server.servlet.context-path=/api

server.port=2121
spring.datasource.url=jdbc:mysql://localhost:3306/avis_utilisateurs?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=yann1212

spring.jpa.hibernate.ddl-auto=update
